language: python
python:
  - "3.7"
  # command to run tests
script:
  - python3 -m unittest myapp_test

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: master
